Connection OK -> 08/05/2025, 07:03:46
Connection OK -> 08/05/2025, 07:05:43
Connection OK -> 08/05/2025, 07:24:24
Connection OK -> 08/05/2025, 07:24:28
Error : get_hackerone_programs() takes 1 positional argument but 2 were given -> 08/05/2025, 07:24:28
Connection OK -> 08/05/2025, 07:27:43
Bugcrowd Data Inserting Successfully -> 08/05/2025, 07:27:43
Connection OK -> 08/05/2025, 07:27:45
Connection OK -> 08/05/2025, 08:24:29
Bugcrowd Data Inserting Successfully -> 08/05/2025, 08:24:30
Connection OK -> 08/05/2025, 08:24:31
Connection OK -> 08/05/2025, 09:02:33
Bugcrowd Data Inserting Successfully -> 08/05/2025, 09:02:34
Connection OK -> 08/05/2025, 09:02:37
Connection OK -> 08/05/2025, 10:09:28
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:09:29
Connection OK -> 08/05/2025, 10:09:53
Connection OK -> 08/05/2025, 10:11:04
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:11:05
Connection OK -> 08/05/2025, 10:11:07
Connection OK -> 08/05/2025, 10:14:03
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:14:04
Connection OK -> 08/05/2025, 10:14:06
Connection OK -> 08/05/2025, 10:18:03
Erorr as column watchers_discoverdprogram.lable does not exist
LINE 1: ...pe", "watchers_discoverdprogram"."discovered_at", "watchers_...
                                                             ^
HINT:  Perhaps you meant to reference the column "watchers_discoverdprogram.label". -> 08/05/2025, 10:18:03
Connection OK -> 08/05/2025, 10:18:05
Connection OK -> 08/05/2025, 10:18:20
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:18:21
Connection OK -> 08/05/2025, 10:18:23
Connection OK -> 08/05/2025, 10:18:43
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:18:44
Connection OK -> 08/05/2025, 10:18:46
Connection OK -> 08/05/2025, 10:21:27
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:21:28
Connection OK -> 08/05/2025, 10:21:32
Connection OK -> 08/05/2025, 10:22:53
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:22:54
Connection OK -> 08/05/2025, 10:23:01
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:23:01
Connection OK -> 08/05/2025, 10:23:12
Failed to retrieve data: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /arkadiyt/bounty-targets-data/master/data/hackerone_data.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1020)'))). Retrying in 5 seconds... -> 08/05/2025, 10:23:17
Connection OK -> 08/05/2025, 10:23:46
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:23:48
Connection OK -> 08/05/2025, 10:24:43
Connection OK -> 08/05/2025, 10:24:43
Connection OK -> 08/05/2025, 10:24:43
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:24:44
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:24:44
Bugcrowd Data Inserting Successfully -> 08/05/2025, 10:24:45
Connection OK -> 08/05/2025, 10:24:49
Connection OK -> 08/05/2025, 10:24:51
Connection OK -> 08/05/2025, 10:24:52
